-- MySQL Script generated by MySQL Workbench
-- Mon Aug 25 23:44:42 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `Animais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Animais` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Animais` (
  `id_Código` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  ` Ano de Nascimento` DATE NOT NULL,
  `Raça` VARCHAR(45) NOT NULL,
  `id_CPF` INT NOT NULL,
  PRIMARY KEY (`id_Código`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Clientes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Clientes` (
  `id_CPF` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Telefone` INT NOT NULL,
  PRIMARY KEY (`id_CPF`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Consultas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Consultas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Consultas` (
  `id_Data` INT NOT NULL,
  `Hora` TIME NOT NULL,
  `Motivo` VARCHAR(200) NOT NULL,
  `id_Código` INT NOT NULL,
  `id_CRMv` INT NOT NULL,
  PRIMARY KEY (`id_Data`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Veterinários`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Veterinários` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Veterinários` (
  `id_CRMv` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Data de Admissão` DATE NOT NULL,
  `Salário` FLOAT NOT NULL,
  PRIMARY KEY (`id_CRMv`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
